export const NAVBAR = {
  NAV_DESKTOP_WIDTH: 280,
  NAV_COLLAPSE_WIDTH: 88,
  DASHBOARD_ITEM_ROOT_HEIGHT: 48,
  DASHBOARD_ITEM_SUB_HEIGHT: 40,
};

export const HEADER = {
  HEADER_DESKTOP_OFFSET_HEIGHT: 64,
  HEADER_DESKTOP_HEIGHT: 88,
};
